# Generated by Django 4.2.3 on 2023-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_addtolistmodel_priorityis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
